#ifndef DRAWING_ENUMS_HPP
#define DRAWING_ENUMS_HPP

namespace Ego
{

enum BufferHint
{
	BUFFER_HINT_STREAM,
	BUFFER_HINT_STATIC,
	BUFFER_HINT_DYNAMIC,
};

enum MeshTopology
{
	MESH_TOPOLOGY_POINT_LIST,
	MESH_TOPOLOGY_LINE_LIST,
	MESH_TOPOLOGY_LINE_STRIP,
	MESH_TOPOLOGY_TRIANGLE_LIST,
	MESH_TOPOLOGY_TRIANGLE_STRIP,
	MESH_TOPOLOGY_TRIANGLE_FAN,
};

enum TextureFiltering
{
	TEXTURE_FILTERING_NEAREST = 0,
	TEXTURE_FILTERING_LINEAR = 1,
// 	TEXTURE_FILTERING_CUBIC = 2,
};

enum TextureWrap
{
	TEXTURE_WRAP_REPEAT = 0,
	TEXTURE_WRAP_MIRRORED_REPEAT = 1,
	TEXTURE_WRAP_CLAMP_TO_EDGE = 2,
// 	TEXTURE_WRAP_CLAMP_TO_BORDER = 3,
// 	TEXTURE_WRAP_MIRROR_CLAMP_TO_EDGE =4,
};

enum VSyncState
{
	VSYNC_STATE_DISABLED,
	VSYNC_STATE_ENABLED,
	VSYNC_STATE_ADAPTIVE,
};

} // namespace Ego

#endif // DRAWING_ENUMS_HPP
